# Generated by Django 2.2.4 on 2020-11-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_auto_20201111_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
    ]
