# Generated by Django 2.2.4 on 2020-11-11 02:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20201111_0319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
